### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Doug-AWS** [awsdocs/aws-ruby-developer-guide#25]
Are there any services you would like to see examples in Ruby? Or more examples? Or a specific use case?

How about a multi-service example? Any ideas?

**Comment by coderjolly** [comment]
could u please more what are you looking for ?

**Comment by sidsrvstv** [comment]
I would like to help on this issue. Could you describe to me an issue I can try resolving?

**Comment by Doug-AWS** [comment]
Since no one has asked for a sample, I'm closing this issue.
