### ISSUE TITLE
All of the source code examples are missing

### ISSUE THREAD

**Issue by copiousfreetime** [awsdocs/aws-ruby-developer-guide#4]
Just 2 days ago I was looking at the docs on amazon and the recipes with actual source code were there. It now appears all the actual example ruby code is missing and there are just headers here.

It looks like all the example code is over in https://github.com/awsdocs/aws-doc-sdk-examples but none of that is in the deployed docs on http://docs.aws.amazon.com/sdk-for-ruby/v2/developer-guide/ec2-recipes.html

**Comment by Doug-AWS** [comment]
I'm on it.

**Comment by Doug-AWS** [comment]
The examples should be back. Feel free to beat me about the head if anything else is missing!

**Comment by Doug-AWS** [comment]
Fixed.
