### ISSUE TITLE
S3 bucket Lifecycle Rule config template examples aren't correct

### ISSUE THREAD

**Issue by weedySeaDragon** [awsdocs/aws-ruby-developer-guide#45]
The code examples on the  page **_Creating a LifeCycle Rule Configuration Template for an Amazon S3 Bucket_**
https://github.com/awsdocs/aws-ruby-developer-guide/blob/main/doc_source/s3-example-create-policy-template.md
are not correct.

**1.  Loop does not generate the correct output**
The loop in this section:
```
require 'aws-sdk'

s3 = Aws::S3::Client.new(region: 'us-west-2')
resp = s3.get_bucket_lifecycle_configuration(bucket: 'default')

resp.rules.each do |rule|
  rule.to_hash.to_json
end
```

is supposed to create this output:
``` [{"expiration":{"date":null,"days":425},"id":"default","prefix":"","status":"Enabled","transitions":[{"date":null,"days":30,"storage_class":"STANDARD_IA"},{"date":null,"days":60,"storage_class":"GLACIER"}],"noncurrent_version_transitions":[],"noncurrent_version_expiration":null}]```

but that loop does not create _any_ output.

If the intent was to create an array with the rules converted to Hashes, then the code should be:
```
rule_hashes = resp.rules.map {|rule| rule.to_h.to_json }
```

**2.  Example code with `to_map` and `to_json` methods  is never used**
The code inserted into the `Aws::S3::Types` is never used.  Perhaps the original intent of the example was to save a LifecycleConfiguration as YML and then read it back in, in which case those methods might make sense.

**3. `.put_lifecycle_configuration` is not working if the configuration uses a filter with `and:`**
So the example won't work for anything but a simple configuration. In which case this process does not save you any time.  (I can accomplish it totally through the SDK; no need to create a lifecycle configuration using the console.)

I am using ruby 2.6.6 and the following:
aws-sdk-core (3.109.1)
aws-sdk-kms (1.39.0)
aws-sdk-s3 (1.83.0)
aws-sigv4 (1.2.2)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
