### ISSUE TITLE
ec2-managing-instances - broken ruby conventions

### ISSUE THREAD

**Issue by rjhornsby** [awsdocs/aws-ruby-developer-guide#46]
This isn't meant to be pedantic, as it did confuse me trying to read the code. It also probably doesn't set a great example for novice ruby devs. In doc_source/ec2-example-managing-instances.md, methods use the ruby `?` signature.

`def instance_stopped?(ec2_client, instance_id) ...`

This `light_on?` style is intended to be a question, an evaluation - "is \<condition\> true?". Here the method body is immediately taking action and modifying state to achieve a `true` condition:

`ec2_client.stop_instances(instance_ids: [instance_id])`

A method which modifies state should have a name indicating such, ie `def instance_stop` - a present tense verb. A method that is meant to evaluate the state makes sense as a past tense verb `stopped` and should be followed by `?` indicating to the reader that the method is an interrogatory, and can be expected to return a boolean.

If the action method wishes to return a boolean to indicate success/failure, that too makes sense. However, "Are you stopped?" is not the same thing as "stop"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
